<?php
declare(strict_types=1);
require __DIR__.'/../_private/server/booking-review-ui.php';
function staff_escape(string $value): string {return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');}
$checks=0;
function expect(bool $condition,string $message): void {global $checks; if(!$condition)throw new RuntimeException($message); $checks++;}
$row=['reschedule_required'=>0,'deposit_paid_at'=>'paid','approved_at'=>'reviewed'];
$claim=['state'=>'confirmed','invitation_state'=>'sent'];
$life=['state'=>'active'];
$mail=['submission_state'=>'sent_observed','crm_state'=>'associated'];
$workflow=['link'=>true,'can_send'=>false,'can_resume_draft'=>false];
$next=static fn(array $r=[],?array $c=null,array $l=[],bool $pending=false,?array $change=null,?array $m=null,?array $cm=null,?array $w=null,bool $job=false):array=>staff_booking_next(array_replace($row,$r),$c??$claim,array_replace($life,$l),$pending,$change,$m??$mail,$cm,$w??$workflow,$job);
expect($next()[1]==='Appointment confirmed','Confirmed appointment offers management without manufacturing another required action.');
expect($next([],null,[],true,['state'=>'applying'])[1]==='Verify the saved appointment change','Uncertain operation takes priority over manager actions.');
expect($next([],null,[],false,['state'=>'pending'])[0]==='appointment','Requested window directs staff to the explicit decision.');
expect($next([],null,[],false,null,null,['submission_state'=>'accepted'])[1]==='Verify the previous change notice','Unverified old notice is distinct from a pending new request.');
expect($next([],null,['state'=>'cancelled'])[0]==='appointment','Cancelled booking offers its saved status, not calendar creation.');
expect($next(['reschedule_required'=>1])[0]==='review','Declined rush keeps the paid booking and directs rescheduling.');
expect($next(['deposit_paid_at'=>null])[0]==='review','Unpaid booking does not proceed to calendar.');
expect($next(['approved_at'=>null])[0]==='review','Paid booking needs review before confirmation.');
expect($next([],null,[],false,null,null,null,['link'=>false])[0]==='readiness','Missing contact goes to readiness.');
expect(staff_booking_next($row,null,$life,false,null,$mail,null,$workflow,false)[0]==='calendar','Reviewed booking without a saved event goes to confirmation.');
expect($next([],['state'=>'uncertain','invitation_state'=>'none'])[1]==='Verify the saved calendar result','Uncertain calendar never offers duplicate creation.');
expect($next([],null,[],false,null,null,null,['link'=>true,'can_resume_draft'=>true])[0]==='readiness','Existing draft uses explicit recovery.');
expect($next([],['state'=>'confirmed','invitation_state'=>'none'],[],false,null,null,null,['link'=>true,'can_send'=>true])[0]==='calendar','Ready invitation is a separate explicit step.');
expect($next([],['state'=>'confirmed','invitation_state'=>'none'])[0]==='readiness','Blocked invitation goes to the prerequisite.');
expect($next([],null,[],false,null,['submission_state'=>'accepted','crm_state'=>'pending'])[0]==='readiness','Submitted mail is not described as verified.');
expect($next([],null,[],false,null,['submission_state'=>'sent_observed','crm_state'=>'pending'])[0]==='readiness','CRM recovery remains separate from verified sending.');
expect($next([],null,[],false,null,null,null,null,true)[0]==='onsite','Completed onsite bill remains available for payment/Production.');
expect(staff_booking_step_for_action('lifecycle_recover_notice')==='appointment','Recovery POST returns to its relevant screen.');
expect(staff_booking_step_for_action('job_complete')==='onsite','Closeout feedback stays with the job.');
expect(staff_booking_step_for_action('review_paid')==='readiness','Saving review leads to its readiness results.');
$screens=['appointment'=>['label'=>'Manage Appointment','html'=>'<form id="original"><input name="agreed" type="checkbox" required></form>'],'onsite'=>['label'=>'Onsite & Vendor','html'=>'<details id="onsite-closeout"><summary>Onsite Closeout</summary>Original services</details>']];
$_GET=[];$html=staff_booking_screens('AB0000000A',$screens,$next(),'');
expect(str_contains($html,'data-booking-screen="overview"><section'),'Overview is the first screen.');
expect(substr_count($html,' hidden')===2,'Other screens are hidden while original guarded forms remain intact.');
expect(str_contains($html,'id="closeout-shortcut"><summary>'),'Closeout shortcut defaults collapsed.');
$_GET=['step'=>'appointment'];$html=staff_booking_screens('AB0000000A',$screens,$next(),'');
expect(str_contains($html,'data-booking-screen="appointment" aria-labelledby'),'Requested screen is visible.');
$_GET=['step'=>['appointment']];$html=staff_booking_screens('AB0000000A',$screens,$next(),'');
expect(str_contains($html,'data-booking-screen="overview"><section'),'Malformed screen selection safely returns to overview.');
$_GET=['step'=>'onsite'];$html=staff_booking_screens('AB0000000A',$screens,$next(),'lifecycle_recover_notice');
expect(str_contains($html,'data-booking-screen="appointment" aria-labelledby'),'POST feedback follows action, not stale navigation.');
$screens['review']=['label'=>'Review Request','html'=>'Original review form'];
$screens['readiness']=['label'=>'Readiness','html'=>'Connection checks','available'=>false];
$html=staff_booking_screens('AB0000000A',$screens,$next(),'review_paid');
expect(str_contains($html,'data-booking-screen="review" aria-labelledby'),'Failed paid review stays with the form needing correction.');
expect(!str_contains($html,'step=readiness"'),'Unreviewed booking does not offer readiness navigation.');
$screens['readiness']['available']=true;
$html=staff_booking_screens('AB0000000A',$screens,$next(),'review_paid');
expect(str_contains($html,'data-booking-screen="readiness" aria-labelledby'),'Successful paid review proceeds to readiness.');
expect(staff_booking_next($row,$claim,$life,false,null,$mail,['submission_state'=>'sent_observed','crm_state'=>'pending'],$workflow,false)[0]==='appointment','Saved change still directs CRM recovery after sent-copy verification.');
expect(staff_booking_next($row,$claim,$life,false,null,$mail,['submission_state'=>'sent_observed','crm_state'=>'associated','delivery_state'=>'unverified'],$workflow,false,false,true)[0]==='appointment','Observable missing change receipt directs recovery.');
expect(staff_booking_next($row,$claim,$life,false,null,$mail,null,$workflow,false,true)[0]==='readiness','Observable missing original invitation receipt directs recovery.');
expect(staff_booking_next($row,$claim,$life,false,null,$mail,null,$workflow,false,false)[1]==='Appointment confirmed','Unavailable external recipient evidence does not force endless recovery.');
echo "booking-review-ui: PASS ($checks checks)\n";
