<?php
declare(strict_types=1);
$done=false;register_shutdown_function(static function()use(&$done){if(!$done){fwrite(STDERR,"Vendor assertions did not complete.\n");exit(1);}});
$root=sys_get_temp_dir().'/sitesee-vendor-'.bin2hex(random_bytes(8));mkdir($root,0700);mkdir($root.'/server',0700);
foreach(glob(__DIR__.'/../_private/server/*.php') as $p)copy($p,$root.'/server/'.basename($p));
foreach(glob(__DIR__.'/../_private/*.php') as $p)copy($p,$root.'/'.basename($p));
putenv('SITESEE_REAL_ESTATE_SITE_URL=https://vendor-test.example');
require $root.'/server/vendor-access.php';
function check(bool $ok,string $why): void{if(!$ok)throw new RuntimeException($why);}
function rejects(callable $f,string $why): void{try{$f();}catch(InvalidArgumentException){return;}throw new RuntimeException('Accepted: '.$why);}
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);vendor_schema($db);$now=time();
$id=vendor_save($db,'','','Vendor One','3125550130',true);$one=vendor_get($db,$id);
$two=vendor_save($db,'','','Vendor Two','3125550131',true);
check($one['phone']==='+13125550130','Phone normalized');
rejects(fn()=>vendor_save($db,'','','Duplicate','+1 (312) 555-0130',true),'Duplicate phone');
rejects(fn()=>vendor_save($db,$id,'stale','Changed','3125550130',true),'Stale manager save');
rejects(fn()=>vendor_save($db,'','','Vendor',"3125550130\n",true),'Phone controls');
$sends=0;$verifies=0;
$send=static function($phone)use(&$sends){++$sends;return 'VE'.str_repeat('a',32);};
$verify=static function($phone,$sid,$code)use(&$verifies){++$verifies;check($phone==='+13125550130'&&$sid==='VE'.str_repeat('a',32),'Provider bound to exact phone/SID');return $code==='123456';};
$secret=str_repeat('s',40);
$unknown=vendor_phone_request($db,'3125550199','a',$secret,$send,$now);check(strlen($unknown)===64&&$sends===0,'Opaque unknown account sends nothing');
$token=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now);check($sends===1,'One SMS request');
$cooldown=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now+1);check($sends===1,'One-minute SMS cooldown');
check(!vendor_phone_consume($db,$cooldown,'123456',$verify,$now+2)&&$verifies===0,'Opaque throttled token cannot verify');
check(!vendor_phone_consume($db,$token,'wrong',$verify,$now+2)&&$verifies===0,'Malformed codes never call provider');
check(!vendor_phone_consume($db,$token,'000000',$verify,$now+2),'Wrong code rejected');
$accepted=vendor_phone_consume($db,$token,'123456',$verify,$now+3);check($accepted&&$accepted['id']===$id,'Phone verifies vendor identity');
check(!vendor_phone_consume($db,$token,'123456',$verify,$now+4),'Code replay blocked');
$db->exec('DELETE FROM vendor_phone_attempts');
$expired=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now);check(!vendor_phone_consume($db,$expired,'123456',$verify,$now+600),'Code expires exactly at deadline');
$db->exec('DELETE FROM vendor_phone_attempts');
$limited=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now);
for($i=0;$i<5;$i++)check(!vendor_phone_consume($db,$limited,'000000',$verify,$now+1),'Bad code not accepted');
$before=$verifies;check(!vendor_phone_consume($db,$limited,'123456',$verify,$now+2)&&$verifies===$before,'Five guesses exhaust challenge');
$db->exec('DELETE FROM vendor_phone_attempts');
$replaced=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now);
$replacement=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now+61);
check(!vendor_phone_consume($db,$replaced,'123456',$verify,$now+62),'Replacement revokes prior challenge');
check(vendor_phone_consume($db,$replacement,'123456',$verify,$now+62)!==false,'Replacement can verify');
$db->exec('DELETE FROM vendor_phone_attempts');
$revoked=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now);
$during=static function()use($db,$id,$one){vendor_save($db,$id,$one['revision'],'Vendor One','3125550130',false);return true;};
check(!vendor_phone_consume($db,$revoked,'123456',$during,$now+1),'Disabling during provider response fails closed');
$db->exec('DELETE FROM vendor_phone_attempts');$before=$sends;vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now);check($sends===$before,'Disabled account cannot receive SMS');
$disabled=vendor_get($db,$id);vendor_save($db,$id,$disabled['revision'],'Vendor One','3125550130',true);$one=vendor_get($db,$id);
$db->exec('DELETE FROM vendor_phone_attempts');
$lost=vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now);
check(!vendor_phone_consume($db,$lost,'123456',static function(){throw new RuntimeException('uncertain provider response');},$now+1),'Uncertain verification rejected');
check(!vendor_phone_consume($db,$lost,'123456',$verify,$now+2),'Uncertain challenge cannot replay');
$db->exec('DELETE FROM vendor_phone_attempts');
$badSid=vendor_phone_request($db,$one['phone'],'b',$secret,static fn()=>'bad-sid',$now);check(!vendor_phone_consume($db,$badSid,'123456',$verify,$now+1),'Malformed provider SID unusable');
$db->exec('DELETE FROM vendor_phone_attempts');$before=$sends;
for($i=0;$i<6;$i++)vendor_phone_request($db,$one['phone'],'b',$secret,$send,$now+$i*61);
check($sends-$before===5,'Five sends per 15-minute window');
$_SERVER['DOCUMENT_ROOT']=$root.'/public';vendor_session_start();vendor_session_login($one,$now);
check(session_name()==='__Host-sitesee_vendor','Separate host-only cookie');
check(vendor_session_account($db,$now+10)['id']===$id,'Active session');
check(!vendor_session_account($db,$now+1810),'Idle expiry enforced');
vendor_session_login($one,$now);$_SESSION['vendor']['seen']=$now+43199;check(!vendor_session_account($db,$now+43200),'Absolute expiry enforced');
vendor_session_login($one,$now);vendor_save($db,$id,$one['revision'],'Vendor One','3125550132',true);check(!vendor_session_account($db,$now+1),'Phone change revokes session');
session_write_close();
$walk=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($walk as $p)$p->isDir()?rmdir($p->getPathname()):unlink($p->getPathname());rmdir($root);
$done=true;echo "portal-vendor: PASS (separate identities; phone binding; expiry; throttling; replay; revocation during verification; provider uncertainty; isolated sessions)\n";
