<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/real-estate-form-config.php';
if (!real_estate_pricing_has_access()) {
    header('Location: pricing-request.html?pricing_required=1#pricing-access');
    exit;
}
header('Cache-Control: no-store, private, max-age=0');
header('Pragma: no-cache');
header('X-Robots-Tag: noindex, nofollow, noarchive');
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Residential &amp; Commercial Pricing | SiteSee Real Estate</title><meta name="description" content="Build a residential or commercial property media estimate. Choose photography, Matterport, video and media packages, then request your preferred shoot date."><meta name="robots" content="noindex, nofollow">
<link rel="icon" href="assets/images/favicon.png" type="image/png"><link rel="stylesheet" href="assets/css/site.css"><link rel="stylesheet" href="assets/css/pricing.css?v=package-matterport-v15">
<script src="assets/js/site.js" defer></script><script src="pricing-asset.php?asset=quote-engine" defer></script><script src="pricing-asset.php?asset=residential-form" defer></script><script src="pricing-asset.php?asset=commercial-quote-engine" defer></script><script src="pricing-asset.php?asset=commercial-form" defer></script><script src="pricing-asset.php?asset=market-selector" defer></script></head><body data-page="pricing.php">
<a class="skip-link" href="#main-content">Skip To Content</a>
    <header class="site-header"><div class="wrap header-inner">
    <a class="brand" href="index.html" aria-label="SiteSee Real Estate home"><img src="assets/images/sitesee-logo.png" width="180" height="60" alt="SiteSee"><span>Real Estate<br>Division</span></a><a class="header-phone" href="tel:+18002222053">(800) 222-2053</a>
    <button class="menu-toggle" type="button" aria-controls="primary-navigation" aria-expanded="false" hidden>Menu <span aria-hidden="true">☰</span></button>
    <nav id="primary-navigation" aria-label="Primary navigation"><a href="index.html">Home</a><a href="platform.html">Platform</a><a href="services-provided.html">Services Provided</a><a href="our-work.html">Our Work</a><a href="contact.html">Contact</a><a class="nav-cta" href="pricing.php" aria-current="page">Pricing &amp; Quote<span aria-hidden="true">↗</span></a></nav>
    </div></header><main id="main-content">
<section class="quote-hero"><div class="wrap quote-hero-grid"><div class="quote-hero-copy"><p class="eyebrow">Residential &amp; Commercial · Your Property, Your Price</p><h1>A Clear Price.<br>A Stronger Listing.<br><span>Start Here.</span></h1><p class="deck">Build the media collection your listing needs. Choose residential or commercial, enter the property address, and select the services that fit your listing.</p><a class="button primary" href="#property-details">Build Your Quote <span aria-hidden="true">↗</span></a><ol class="quote-steps"><li><span>01 / Your Property</span>Start with the address</li><li><span>02 / Your Media</span>Choose what you need</li><li><span>03 / Your Shoot</span>Request a date</li></ol></div><figure><img src="assets/images/photography/residential/residential-28.webp" alt="Stone home framed by mature trees with warm interior lighting at twilight" width="1600" height="900" fetchpriority="high"></figure></div></section>
<section class="quote-section" id="property-details"><div class="wrap"><section class="quote-panel quote-market-select" aria-labelledby="market-title"><p class="eyebrow dark">Start Here</p><h2 id="market-title">What Type Of Property?</h2><p>Choose the services and pricing designed for your listing.</p><fieldset><legend class="sr-only">Residential Or Commercial</legend><div class="quote-grid"><label class="quote-choice"><input type="radio" name="property-type" value="residential" required><span>Residential<small>Homes, condos and residential listings</small></span></label><label class="quote-choice"><input type="radio" name="property-type" value="commercial" required><span>Commercial<small>Retail, offices, warehouses and industrial properties</small></span></label></div></fieldset><noscript><p>Enable JavaScript to calculate a quote, or email sales@sitesee.ai with your project details.</p></noscript></section><div id="residential-market" hidden><div class="quote-layout"><form id="residential-quote" class="quote-form" action="quote-submit.php" method="post" novalidate><div hidden aria-hidden="true"><label>Company Fax<input name="company_fax" tabindex="-1" autocomplete="off"></label></div>
<section class="quote-panel" aria-labelledby="address-title"><p class="eyebrow dark">01 / Your Property</p><h2 id="address-title">Where Is The Listing?</h2><p>Enter the complete address to open your estimate. All address fields are required.</p><div class="field-grid" id="address-fields">
<div class="field field-wide"><label for="listing-street">Property Street Address</label><input id="listing-street" name="street" type="text" autocomplete="section-property address-line1" maxlength="180" required></div>
<div class="field"><label for="listing-city">City</label><input id="listing-city" name="city" type="text" autocomplete="section-property address-level2" maxlength="100" required></div>
<div class="field"><label for="listing-state">State</label><select id="listing-state" name="state" autocomplete="section-property address-level1" required><option value="">Select State</option><option value="AL">Alabama</option><option value="AK">Alaska</option><option value="AZ">Arizona</option><option value="AR">Arkansas</option><option value="CA">California</option><option value="CO">Colorado</option><option value="CT">Connecticut</option><option value="DE">Delaware</option><option value="DC">District of Columbia</option><option value="FL">Florida</option><option value="GA">Georgia</option><option value="HI">Hawaii</option><option value="ID">Idaho</option><option value="IL">Illinois</option><option value="IN">Indiana</option><option value="IA">Iowa</option><option value="KS">Kansas</option><option value="KY">Kentucky</option><option value="LA">Louisiana</option><option value="ME">Maine</option><option value="MD">Maryland</option><option value="MA">Massachusetts</option><option value="MI">Michigan</option><option value="MN">Minnesota</option><option value="MS">Mississippi</option><option value="MO">Missouri</option><option value="MT">Montana</option><option value="NE">Nebraska</option><option value="NV">Nevada</option><option value="NH">New Hampshire</option><option value="NJ">New Jersey</option><option value="NM">New Mexico</option><option value="NY">New York</option><option value="NC">North Carolina</option><option value="ND">North Dakota</option><option value="OH">Ohio</option><option value="OK">Oklahoma</option><option value="OR">Oregon</option><option value="PA">Pennsylvania</option><option value="RI">Rhode Island</option><option value="SC">South Carolina</option><option value="SD">South Dakota</option><option value="TN">Tennessee</option><option value="TX">Texas</option><option value="UT">Utah</option><option value="VT">Vermont</option><option value="VA">Virginia</option><option value="WA">Washington</option><option value="WV">West Virginia</option><option value="WI">Wisconsin</option><option value="WY">Wyoming</option></select></div>
<div class="field"><label for="listing-zip">ZIP Code</label><input id="listing-zip" name="zip" type="text" autocomplete="section-property postal-code" inputmode="numeric" pattern="[0-9]{5}(-[0-9]{4})?" maxlength="10" required aria-describedby="zip-help"><small id="zip-help">Five digits, or ZIP+4.</small></div>
</div><button class="button primary" id="open-estimate" type="button" disabled aria-controls="estimate-section" aria-expanded="false">Continue To My Estimate <span aria-hidden="true">↓</span></button><noscript><p class="quote-note">Enable JavaScript to calculate a quote, or email sales@sitesee.ai with your property details.</p></noscript></section>
<div class="quote-lock" id="estimate-lock"><strong>Your Estimate Is Next.</strong><p>Choose individual services or a media package after entering your listing address.</p></div>
<section id="estimate-section" class="quote-panel" hidden aria-labelledby="estimate-title"><p class="eyebrow dark">02 / Your Media</p><h2 id="estimate-title" tabindex="-1">Build Your Property Quote.</h2><p id="quote-address" class="quote-full-address"></p>
<fieldset><legend>Property Category</legend><div class="quote-grid" id="category-options">
<label class="quote-choice"><input type="radio" name="category" value="small" required><span>Small Home / Condo<small>Under 2,000 sq ft · 25–30 photos</small></span></label>
<label class="quote-choice"><input type="radio" name="category" value="average" required checked><span>Average Home<small>2,000–4,000 sq ft · 30–50 photos</small></span></label>
<label class="quote-choice"><input type="radio" name="category" value="large" required><span>Large Home<small>4,000–5,000 sq ft · 50–60 photos</small></span></label>
<label class="quote-choice"><input type="radio" name="category" value="luxury" required><span>Luxury Home<small>5,000–10,000 sq ft · 50+ photos</small></span></label>
</div></fieldset>
<div class="quote-size"><label for="property-sqft">Property Size · Square Feet</label><input id="property-sqft" name="sqft" type="number" min="2000" max="4000" step="1" value="2680" required></div><input id="property-slider" type="range" min="2000" max="4000" step="1" value="2680" aria-label="Property size in square feet"><div class="quote-range-labels"><span id="range-min">2,000 sq ft</span><span id="range-max">4,000 sq ft</span></div>
<fieldset><legend>Choose A Package Or Individual Services</legend><div class="quote-grid">
<label class="quote-choice"><input type="radio" name="package" value="custom" required checked><span>Individual Services<small>Select exactly what your listing needs.</small></span></label>
<label class="quote-choice"><input type="radio" name="package" value="silver" required><span>Silver · $220<small>Up to 1,600 sq ft. 25 HDR photos and a property website.</small></span></label>
<label class="quote-choice"><input type="radio" name="package" value="gold" required><span>Gold · $499<small>Up to 3,000 sq ft. 35 HDR photos, 1-minute video, property website and 2D floor plan.</small></span></label>
<label class="quote-choice"><input type="radio" name="package" value="platinum" required><span>Platinum · $995<small>Up to 5,800 sq ft. 50+ HDR photos, 2-minute video, website, drone aerials and 2D floor plan.</small></span></label>
</div></fieldset>
<h3>Services &amp; Additions</h3><p class="quote-note">Photography is required and stays selected. Package inclusions are selected automatically and charged once.</p><div id="quote-services"></div>
<p class="quote-note">*Minimum Matterport fee: $69. Properties up to 1,150 sq ft are charged $69; larger properties are charged $0.06 per sq ft, capped at $499 up to 10,000 sq ft.</p>
<div class="quote-error" id="estimate-error" role="alert" hidden></div><p id="custom-quote-note" class="quote-note" hidden></p>
<div class="quote-inline-total" aria-live="polite"><span>Your Estimated Total</span><strong id="estimate-inline-total">—</strong><small id="estimate-inline-time"></small></div>
<button class="button primary" type="button" id="review-estimate" aria-controls="request-section" aria-expanded="false">Continue With This Estimate <span aria-hidden="true">↓</span></button>
</section>
<section class="quote-panel" id="request-section" hidden aria-labelledby="request-title"><p class="eyebrow dark">03 / Your Details &amp; Preferred Date</p><h2 id="request-title" tabindex="-1">Let’s Plan Your Listing.</h2><p>All fields, including your preferred date and time, are required.</p><div class="field-grid" id="agent-fields">
<div class="field"><label for="agent-first">First Name</label><input id="agent-first" name="first" autocomplete="given-name" maxlength="100" required></div>
<div class="field"><label for="agent-last">Last Name</label><input id="agent-last" name="last" autocomplete="family-name" maxlength="100" required></div>
<div class="field field-wide"><label for="agent-company">Company Name</label><input id="agent-company" name="company" autocomplete="organization" maxlength="140" required></div>
<div class="field"><label for="agent-email">Email Address</label><input id="agent-email" name="email" type="email" autocomplete="email" maxlength="180" required></div>
<div class="field"><label for="agent-phone">Phone Number</label><input id="agent-phone" name="phone" type="tel" autocomplete="tel" maxlength="35" required></div>
<div class="field field-wide"><label for="agent-opt-out">Exclude You From Mailing Lists?</label><select id="agent-opt-out" name="optOut" required><option value="">Select Your Preference</option><option value="Yes">Yes — exclude me from mailing lists</option><option value="No">No — updates are welcome</option></select></div>
</div><div class="quote-actions"><button class="button secondary" type="button" id="email-self">Email My Quote To Me</button><button class="button secondary" type="button" id="copy-quote">Copy Quote</button></div><p class="quote-email-help">Email My Quote To Me sends a server-validated copy to your address. Copy Quote keeps a local copy-and-paste option.</p>
<div class="field-grid quote-date-grid" id="appointment-fields"><div class="field"><label for="shoot-date" id="date-label">Preferred Shoot Date (Required For A Request)</label><input type="date" id="shoot-date" name="date" required></div><div class="field"><label for="shoot-time" id="time-label">Preferred Start Time · Central Time</label><input type="time" id="shoot-time" name="time" step="900" required></div></div>
<p class="quote-note">Your preferred date and time are a request. We will confirm availability and the appointment with you.</p><div class="quote-actions"><button class="button primary" type="submit" id="request-shoot">Request My Preferred Date <span aria-hidden="true">↗</span></button></div><p class="privacy-note">Your details are used to respond to this property request. <a href="https://sitesee.ai/privacy.html" target="_blank" rel="noopener noreferrer">Privacy Policy<span class="sr-only"> (opens in a new tab)</span></a>.</p><div id="request-status" class="quote-status" hidden role="status" aria-live="polite"></div>
</section></form><aside class="quote-sidebar" aria-label="Your quote summary"><section class="quote-summary"><p class="eyebrow">Your Property. Your Plan.</p><div id="summary-locked"><h3>A Quote Built Around Your Listing.</h3><p>Start with the property address. Your selected media and estimated time will appear here.</p></div><div id="summary-unlocked" hidden aria-live="polite"><p id="summary-property"></p><div class="quote-summary-total" id="summary-total">—</div><p id="summary-subtotal" hidden></p><ul id="summary-lines"></ul><h3 id="site-time-title">Estimated Time On Site</h3><p id="summary-duration">—</p><p id="summary-breakdown"></p><p id="summary-time-note"></p><p>Estimates cover the selected media. Final scope and appointment availability are confirmed with you.</p></div></section>
<figure class="quote-sidebar-photo"><img src="assets/images/photography/residential/residential-15.webp" alt="Bright kitchen with a generous island and adjoining dining space overlooking the water" width="1600" height="900" loading="lazy"></figure><div class="quote-sidebar-copy"><h3>Help Buyers See The Whole Picture.</h3><p>Pair inviting photography with the media that makes your listing easier to explore.</p><a href="residential-photography.html">Explore Our Residential Photography ↗</a><p>Planning commercial media or platform subscriptions? <a href="contact.html">Discuss Your Project</a>.</p></div></aside></div></div><div id="commercial-market" hidden><div class="quote-layout"><form id="commercial-quote" class="quote-form" action="quote-submit.php" method="post" novalidate><div hidden aria-hidden="true"><label>Company Fax<input name="company_fax" tabindex="-1" autocomplete="off"></label></div>
<section class="quote-panel" aria-labelledby="c-address-title"><p class="eyebrow dark">01 / Your Property</p><h2 id="c-address-title">Where Is The Listing?</h2><p>Enter the complete address to open your estimate. All address fields are required.</p><div class="field-grid" id="c-address-fields">
<div class="field field-wide"><label for="c-listing-street">Property Street Address</label><input id="c-listing-street" name="street" type="text" autocomplete="section-property address-line1" maxlength="180" required></div>
<div class="field"><label for="c-listing-city">City</label><input id="c-listing-city" name="city" type="text" autocomplete="section-property address-level2" maxlength="100" required></div>
<div class="field"><label for="c-listing-state">State</label><select id="c-listing-state" name="state" autocomplete="section-property address-level1" required><option value="">Select State</option><option value="AL">Alabama</option><option value="AK">Alaska</option><option value="AZ">Arizona</option><option value="AR">Arkansas</option><option value="CA">California</option><option value="CO">Colorado</option><option value="CT">Connecticut</option><option value="DE">Delaware</option><option value="DC">District of Columbia</option><option value="FL">Florida</option><option value="GA">Georgia</option><option value="HI">Hawaii</option><option value="ID">Idaho</option><option value="IL">Illinois</option><option value="IN">Indiana</option><option value="IA">Iowa</option><option value="KS">Kansas</option><option value="KY">Kentucky</option><option value="LA">Louisiana</option><option value="ME">Maine</option><option value="MD">Maryland</option><option value="MA">Massachusetts</option><option value="MI">Michigan</option><option value="MN">Minnesota</option><option value="MS">Mississippi</option><option value="MO">Missouri</option><option value="MT">Montana</option><option value="NE">Nebraska</option><option value="NV">Nevada</option><option value="NH">New Hampshire</option><option value="NJ">New Jersey</option><option value="NM">New Mexico</option><option value="NY">New York</option><option value="NC">North Carolina</option><option value="ND">North Dakota</option><option value="OH">Ohio</option><option value="OK">Oklahoma</option><option value="OR">Oregon</option><option value="PA">Pennsylvania</option><option value="RI">Rhode Island</option><option value="SC">South Carolina</option><option value="SD">South Dakota</option><option value="TN">Tennessee</option><option value="TX">Texas</option><option value="UT">Utah</option><option value="VT">Vermont</option><option value="VA">Virginia</option><option value="WA">Washington</option><option value="WV">West Virginia</option><option value="WI">Wisconsin</option><option value="WY">Wyoming</option></select></div>
<div class="field"><label for="c-listing-zip">ZIP Code</label><input id="c-listing-zip" name="zip" type="text" autocomplete="section-property postal-code" inputmode="numeric" pattern="[0-9]{5}(-[0-9]{4})?" maxlength="10" required aria-describedby="c-zip-help"><small id="c-zip-help">Five digits, or ZIP+4.</small></div>
</div><button class="button primary" id="c-open-estimate" type="button" disabled aria-controls="c-estimate-section" aria-expanded="false">Continue To My Estimate <span aria-hidden="true">↓</span></button><noscript><p class="quote-note">Enable JavaScript to calculate a quote, or email sales@sitesee.ai with your property details.</p></noscript></section>
<div class="quote-lock" id="c-estimate-lock"><strong>Your Estimate Is Next.</strong><p>Choose commercial media and a usage license after entering your listing address.</p></div>
<section id="c-estimate-section" class="quote-panel" hidden aria-labelledby="c-estimate-title"><p class="eyebrow dark">02 / Commercial Media</p><h2 id="c-estimate-title" tabindex="-1">Build Your Commercial Quote.</h2><p id="c-quote-address" class="quote-full-address"></p>
<fieldset><legend>Commercial Property Category</legend><div class="quote-grid">
<label class="quote-choice"><input type="radio" name="category" value="small" required checked><span>Small Commercial / Retail<small>Up to 10,000 sq ft · 25–30 photos · $750</small></span></label>
<label class="quote-choice"><input type="radio" name="category" value="mid" required><span>Warehouse / Office<small>10,000–50,000 sq ft · 30–45 photos · $1,200</small></span></label>
<label class="quote-choice"><input type="radio" name="category" value="large" required><span>Factory / Industrial<small>50,000–250,000 sq ft · 45–55 photos · $2,500+</small></span></label>
</div></fieldset>
<p class="quote-note">Photography is included: Small $750, Warehouse / Office $1,200, Factory / Industrial $2,500. Additional photographs increase the shoot fee. Projects above 250,000 sq ft are quoted directly.</p>
<fieldset><legend>Photography Quantity</legend><p id="c-photo-inclusions" class="quote-note">25–30 photos included. Additional photos above 30 are $30 each. Maximum 35 total photos.</p><div class="quote-size"><label for="c-photo-slider">Total Finished Photographs</label><output id="c-photo-count" for="c-photo-slider" data-range-value>30</output></div><input id="c-photo-slider" name="photoCount" type="range" min="25" max="35" step="1" value="30" aria-label="Total finished commercial photographs"><div class="quote-range-labels"><span id="c-photo-range-min">25 photos</span><span id="c-photo-range-max">35 photos maximum</span></div><p id="c-photo-addition" class="quote-note" aria-live="polite"></p></fieldset>
<div class="quote-inline-total" aria-live="polite"><span>Photography Estimate</span><strong id="c-photography-price">—</strong><small>Before licensing and optional services</small></div><h3>Services &amp; Additions</h3><div id="c-quote-services"></div><p class="quote-note">*Matterport is $0.10 per scanned sq ft with a $199 minimum. Enter the area to scan independently of photography. Six months of hosting are included; additional months are $6.99 each, or $4.99 when paid in advance. Single 360° photos are a $25 add-on to Matterport and require a SiteSee platform subscription.</p>
<fieldset><legend>Property Delivery</legend><div class="quote-grid">
<label class="quote-choice"><input type="radio" name="delivery" value="files" checked required><span>Media Files Only<small>Finished files ready for your listing. No platform fee.</small></span></label>
<label class="quote-choice"><input type="radio" name="delivery" value="website" required><span>Independent Property Website<small id="c-website-note">$175 for a dedicated listing website with your property media and details.</small></span></label>
</div></fieldset>
<fieldset id="c-license-fields"><legend>Media Usage License</legend><div class="quote-grid">
<label class="quote-choice"><input type="radio" name="licenseType" value="term" checked required><span>Extended License</span></label>
<label class="quote-choice"><input type="radio" name="licenseType" value="unlimited" required><span>Unlimited License</span></label>
</div><div id="c-license-term-controls" class="quote-extra"><div class="quote-size"><label for="c-license-months">Total License Term · Months</label><output for="c-license-months" data-range-value>6</output></div><input id="c-license-months" name="licenseMonths" type="range" min="6" max="18" step="1" value="6"><div class="quote-range-labels"><span>6 months</span><span>18 months</span></div></div>
<p id="c-license-calculation" class="quote-note" aria-live="polite"></p></fieldset>
<fieldset id="c-hosting-controls" hidden><legend>Matterport Hosting</legend><p class="quote-note">6 Months Matterport hosting included. Thereafter $6.99 per month. Pay in advance is $4.99 per month.</p><label class="quote-choice"><input type="checkbox" id="c-hosting-prepaid" name="hostingPrepaid" disabled><span>Pay In Advance</span></label><div class="quote-extra"><div class="quote-size"><label for="c-hosting-months">Total Hosting Term · Months</label><output for="c-hosting-months" data-range-value>6</output></div><input id="c-hosting-months" name="hostingMonths" type="range" min="6" max="18" step="1" value="6" disabled><div class="quote-range-labels"><span>6 months included</span><span>18 months total</span></div></div><p id="c-hosting-calculation" class="quote-note" aria-live="polite"></p></fieldset>
<div class="quote-error" id="c-estimate-error" role="alert" hidden></div><p id="c-custom-quote-note" class="quote-note" hidden></p>
<div class="quote-inline-total" aria-live="polite"><span>Your Estimated Total</span><strong id="c-estimate-inline-total">—</strong><small id="c-estimate-inline-time"></small></div><button class="button primary" type="button" id="c-review-estimate" aria-controls="c-request-section" aria-expanded="false">Continue With This Estimate <span aria-hidden="true">↓</span></button></section>
<section class="quote-panel" id="c-request-section" hidden aria-labelledby="c-request-title"><p class="eyebrow dark">03 / Your Details &amp; Preferred Date</p><h2 id="c-request-title" tabindex="-1">Let’s Plan Your Listing.</h2><p>All fields, including your preferred date and time, are required.</p><div class="field-grid" id="c-agent-fields">
<div class="field"><label for="c-agent-first">First Name</label><input id="c-agent-first" name="first" autocomplete="given-name" maxlength="100" required></div>
<div class="field"><label for="c-agent-last">Last Name</label><input id="c-agent-last" name="last" autocomplete="family-name" maxlength="100" required></div>
<div class="field field-wide"><label for="c-agent-company">Company Name</label><input id="c-agent-company" name="company" autocomplete="organization" maxlength="140" required></div>
<div class="field"><label for="c-agent-email">Email Address</label><input id="c-agent-email" name="email" type="email" autocomplete="email" maxlength="180" required></div>
<div class="field"><label for="c-agent-phone">Phone Number</label><input id="c-agent-phone" name="phone" type="tel" autocomplete="tel" maxlength="35" required></div>
<div class="field field-wide"><label for="c-agent-opt-out">Exclude You From Mailing Lists?</label><select id="c-agent-opt-out" name="optOut" required><option value="">Select Your Preference</option><option value="Yes">Yes — exclude me from mailing lists</option><option value="No">No — updates are welcome</option></select></div>
</div><div class="quote-actions"><button class="button secondary" type="button" id="c-email-self">Email My Quote To Me</button><button class="button secondary" type="button" id="c-copy-quote">Copy Quote</button></div><p class="quote-email-help">Email My Quote To Me sends a server-validated copy to your address. Copy Quote keeps a local copy-and-paste option.</p>
<div class="field-grid quote-date-grid" id="c-appointment-fields"><div class="field"><label for="c-shoot-date" id="c-date-label">Preferred Shoot Date (Required For A Request)</label><input type="date" id="c-shoot-date" name="date" required></div><div class="field"><label for="c-shoot-time" id="c-time-label">Preferred Start Time · Central Time</label><input type="time" id="c-shoot-time" name="time" step="900" required></div></div>
<p class="quote-note">Your preferred date and time are a request. We will confirm availability and the appointment with you.</p><div class="quote-actions"><button class="button primary" type="submit" id="c-request-shoot">Request My Preferred Date <span aria-hidden="true">↗</span></button></div><p class="privacy-note">Your details are used to respond to this property request. <a href="https://sitesee.ai/privacy.html" target="_blank" rel="noopener noreferrer">Privacy Policy<span class="sr-only"> (opens in a new tab)</span></a>.</p><div id="c-request-status" class="quote-status" hidden role="status" aria-live="polite"></div>
</section></form><aside class="quote-sidebar" aria-label="Your quote summary"><section class="quote-summary"><p class="eyebrow">Your Property. Your Plan.</p><div id="c-summary-locked"><h3>A Quote Built Around Your Listing.</h3><p>Start with the property address. Your selected media and estimated time will appear here.</p></div><div id="c-summary-unlocked" hidden aria-live="polite"><p id="c-summary-property"></p><div class="quote-summary-total" id="c-summary-total">—</div><p id="c-summary-subtotal" hidden></p><ul id="c-summary-lines"></ul><h3 id="c-site-time-title">Estimated Time On Site</h3><p id="c-summary-duration">—</p><p id="c-summary-breakdown"></p><p id="c-summary-time-note"></p><p>Estimates cover the selected media. Final scope and appointment availability are confirmed with you.</p></div></section>
<figure class="quote-sidebar-photo"><img src="assets/images/photography/commercial/commercial-05.webp" alt="Glass-fronted commercial office building" width="1600" height="900" loading="lazy"></figure><div class="quote-sidebar-copy"><h3>Show The Space. Explain The Opportunity.</h3><p>Help buyers and tenants assess the building, layout and access before arranging a visit.</p><a href="commercial-services.html">Explore Commercial Services ↗</a><p>Planning several properties or a platform subscription? <a href="contact.html">Discuss Your Project</a>.</p></div></aside></div></div></div></section></main>
<footer class="site-footer"><div class="wrap footer-grid">
    <div class="footer-brand"><a href="index.html"><img src="assets/images/sitesee-logo.png" width="180" height="60" alt="SiteSee"></a><p class="division">Real Estate Division</p><a class="footer-phone" href="tel:+18002222053">(800) 222-2053</a><p>Property media and a connected platform for the way people choose their next space.</p><strong>Show More. Decide Faster.</strong></div>
    <div class="footer-column"><h2>Real Estate</h2><a href="index.html">Home</a><a href="platform.html">Platform</a><a href="platform.html#ai-visualization">AI Decluttering &amp; Redesign</a><a href="platform.html#online-meetings">In-Platform Meetings</a><a href="platform.html#property-notes">Property Notes &amp; Collaboration</a><a href="platform.html#agents-teams-brokerages">For Agents, Teams &amp; Brokerages</a><a href="services-provided.html">Services Provided</a><a href="our-work.html">Our Work</a><a href="contact.html">Contact</a><a href="pricing.php">Pricing &amp; Quote</a></div>
    <div class="footer-column"><h2>Services</h2><a href="residential-services.html">Residential Media Process</a><a href="commercial-services.html">Commercial Media Process</a><a href="services-provided.html#photography">Property Photography</a><a href="services-provided.html#virtual-experiences">Virtual Experiences</a><a href="services-provided.html#drone-aerial">Drone & Aerial Photography</a><a href="services-provided.html#property-video">Property Video</a><a href="services-provided.html#floor-plans">Floor Plans</a><a href="services-provided.html#property-websites">Property Websites</a><a href="services-provided.html#virtual-twilight">Virtual Twilight Photography</a><a href="services-provided.html#media-packages">Media Packages & Custom Coverage</a></div>
    <div class="footer-column"><h2>SiteSee Corporate</h2><a href="https://sitesee.ai/" target="_blank" rel="noopener noreferrer">Corporate Website<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/company.html" target="_blank" rel="noopener noreferrer">About SiteSee<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/platform.html" target="_blank" rel="noopener noreferrer">Operating System<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/resources.html" target="_blank" rel="noopener noreferrer">Resources<span class="sr-only"> (opens in a new tab)</span></a></div>
    </div><div class="wrap footer-legal"><p>© <a href="https://sitesee.ai/copyright.html" target="_blank" rel="noopener noreferrer">2026<span class="sr-only"> (opens in a new tab)</span></a> SiteSee. All rights reserved.</p><div><a href="https://sitesee.ai/privacy.html" target="_blank" rel="noopener noreferrer">Privacy<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/terms.html" target="_blank" rel="noopener noreferrer">Terms<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/marks-trademarks.html" target="_blank" rel="noopener noreferrer">Marks & Trademarks<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/accessibility.html" target="_blank" rel="noopener noreferrer">Accessibility<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/cookies.html" target="_blank" rel="noopener noreferrer">Cookies<span class="sr-only"> (opens in a new tab)</span></a><a href="https://sitesee.ai/sitemap.html" target="_blank" rel="noopener noreferrer">Sitemap<span class="sr-only"> (opens in a new tab)</span></a></div></div></footer></body></html>
