<?php
declare(strict_types=1);
// Included inside both quote forms; the prefix keeps element IDs unique.
$p = $schedulePrefix;
?>
<div class="quote-scheduling" id="<?= $p ?>scheduling-fields">
<section class="quote-policy" id="<?= $p ?>availability-panel" hidden aria-labelledby="<?= $p ?>availability-heading"><h3 id="<?= $p ?>availability-heading">Calendar Availability</h3><p id="<?= $p ?>availability-status" role="status" aria-live="polite">Choose your services and a date to check available arrival windows.</p><div class="quote-grid" id="<?= $p ?>availability-choices"></div><button type="button" class="button secondary" id="<?= $p ?>availability-retry">Check Again</button><p class="quote-note">Suggestions do not reserve a time. Your two-hour arrival window remains subject to SiteSee approval.</p></section>
<fieldset><legend>Agent to meet photographer at the property?</legend><div class="quote-grid"><label class="quote-choice"><input type="radio" name="meetPhotographer" value="Yes" required><span>Yes</span></label><label class="quote-choice"><input type="radio" name="meetPhotographer" value="No" required><span>No</span></label></div></fieldset>
<fieldset id="<?= $p ?>access-fields" hidden><legend>Type of access?</legend><div class="quote-grid"><label class="quote-choice"><input type="radio" name="accessType" value="Lockbox" disabled><span>Lockbox</span></label><label class="quote-choice"><input type="radio" name="accessType" value="Key" disabled><span>Key</span></label></div></fieldset>
<div class="field field-wide" id="<?= $p ?>lockbox-fields" hidden><label for="<?= $p ?>lockbox-code">Lockbox code</label><input id="<?= $p ?>lockbox-code" name="lockboxCode" type="text" inputmode="numeric" pattern="[0-9]{10}" minlength="10" maxlength="10" autocomplete="off" aria-describedby="<?= $p ?>lockbox-help" disabled><small id="<?= $p ?>lockbox-help">Exactly 10 digits, including any leading zeros.</small></div>
<div class="field field-wide" id="<?= $p ?>key-fields" hidden><label for="<?= $p ?>key-location">Key location</label><textarea id="<?= $p ?>key-location" name="keyLocation" rows="3" maxlength="150" disabled></textarea></div>
<div class="field-grid quote-scheduling-notes"><div class="field field-wide"><label for="<?= $p ?>special-requests">Special requests (optional)</label><textarea id="<?= $p ?>special-requests" name="specialRequests" rows="3" maxlength="250"></textarea></div>
<div class="field field-wide"><label for="<?= $p ?>must-have-shots">Must-have shots (optional)</label><textarea id="<?= $p ?>must-have-shots" name="mustHaveShots" rows="3" maxlength="250"></textarea></div></div>
<fieldset><legend>Another contact on site?</legend><label class="quote-check"><input id="<?= $p ?>onsite-different" name="onsiteDifferent" type="checkbox" value="Yes"><span>Yes, a different person will be on site</span></label>
<div class="field-grid quote-contact-fields" id="<?= $p ?>onsite-fields" hidden><div class="field"><label for="<?= $p ?>onsite-name">On-site contact name</label><input id="<?= $p ?>onsite-name" name="onsiteName" maxlength="100" disabled></div><div class="field"><label for="<?= $p ?>onsite-email">On-site contact email</label><input id="<?= $p ?>onsite-email" name="onsiteEmail" type="email" maxlength="180" disabled></div><div class="field"><label for="<?= $p ?>onsite-phone">On-site contact phone</label><input id="<?= $p ?>onsite-phone" name="onsitePhone" type="tel" maxlength="35" disabled></div></div></fieldset>
<fieldset><legend>Additional contact for scheduling?</legend><label class="quote-check"><input id="<?= $p ?>additional-different" name="additionalDifferent" type="checkbox" value="Yes"><span>Yes, include another person when confirming the appointment</span></label>
<div class="field-grid quote-contact-fields" id="<?= $p ?>additional-fields" hidden><div class="field"><label for="<?= $p ?>additional-name">Additional contact name</label><input id="<?= $p ?>additional-name" name="additionalName" maxlength="100" disabled></div><div class="field"><label for="<?= $p ?>additional-email">Additional contact email</label><input id="<?= $p ?>additional-email" name="additionalEmail" type="email" maxlength="180" disabled></div><div class="field"><label for="<?= $p ?>additional-phone">Additional contact phone (optional)</label><input id="<?= $p ?>additional-phone" name="additionalPhone" type="tel" maxlength="35" disabled></div></div></fieldset>
<div class="quote-policy"><h3>24-hour cancellation policy</h3><p>Cancel at least 24 hours before your confirmed appointment for a refund of any deposit paid. If you cancel within 24 hours, your deposit remains a credit toward one rescheduled shoot.</p><label class="quote-check"><input id="<?= $p ?>cancellation-accepted" name="cancellationAccepted" type="checkbox" value="Yes" required><span>I agree to the cancellation policy and understand that my preferred date and two-hour arrival window are pending confirmation. My deposit is refundable if no mutually acceptable date is available.</span></label></div>
</div>
